/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control;

import knowledge_source.ScanFolderController;
import black_board.BlackBoard;
import javax.swing.JOptionPane;
import knowledge_source.CriterionController;

/**
 *
 * @author hoanglvq
 */
public class MainScreen extends javax.swing.JFrame {

    BlackBoard bbObject;

    ScanFolderController sfcObject;
    CriterionController ccObject;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {

        initComponents();

        // initialize Objects
        this.bbObject = new BlackBoard();

        sfcObject = new ScanFolderController();
        ccObject = new CriterionController();

        // register Knowledge Sources to BlackBoard
        bbObject.registerKS(sfcObject);
        bbObject.registerKS(ccObject);

        // register among components
        sfcObject.addComponentListener(ccObject);

        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOF1 = new javax.swing.JButton();
        btnOF2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPath1 = new javax.swing.JTextField();
        txtPath2 = new javax.swing.JTextField();
        btnCompare = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOF1.setText("Open Folder 1");
        btnOF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOF1ActionPerformed(evt);
            }
        });

        btnOF2.setText("Open Folder 2");
        btnOF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOF2ActionPerformed(evt);
            }
        });

        jLabel1.setText(":");

        jLabel2.setText(":");

        btnCompare.setText("Compare");
        btnCompare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCompare, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOF1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOF2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPath2, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                            .addComponent(txtPath1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOF1)
                    .addComponent(jLabel1)
                    .addComponent(txtPath1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOF2)
                    .addComponent(jLabel2)
                    .addComponent(txtPath2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCompare)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOF1ActionPerformed
        if(bbObject.chooseFolder1()){
            this.txtPath1.setText(bbObject.getFolder1Path());
            this.checkTheSameFolders(1);
        }
    }//GEN-LAST:event_btnOF1ActionPerformed

    private void btnOF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOF2ActionPerformed
        if(bbObject.chooseFolder2()){
            this.txtPath2.setText(bbObject.getFolder2Path());
            this.checkTheSameFolders(2);
        } 
    }//GEN-LAST:event_btnOF2ActionPerformed

    private void btnCompareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompareActionPerformed
        bbObject.display();
    }//GEN-LAST:event_btnCompareActionPerformed
    private void checkTheSameFolders(int numFolder) {
        if (bbObject.getFolder1Path().equals(bbObject.getFolder2Path())) {
            JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn 2 folder khác nhau !",
                    "Inane warning",
                    JOptionPane.WARNING_MESSAGE);
            if(numFolder == 1){
                txtPath1.setText("");
                bbObject.emptyListFilesInFolder(1);
                this.btnOF1ActionPerformed(null);
            }else{
                txtPath2.setText("");
                bbObject.emptyListFilesInFolder(2);
                this.btnOF2ActionPerformed(null);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompare;
    private javax.swing.JButton btnOF1;
    private javax.swing.JButton btnOF2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtPath1;
    private javax.swing.JTextField txtPath2;
    // End of variables declaration//GEN-END:variables
}
